export type EsewaInit = {
  /**
   * Amount of product, item, ticket, etc.
   *
   * @currency Rupees
   */
  amt: number;
  /**
   * Tax amount on product, item, ticket etc.
   *
   * @currency Rupees
   * @default 0
   */
  txAmt?: number;
  /**
   * Service charge by merchant on product, item, ticket, etc.
   *
   * @currency Rupees
   * @default 0
   */
  psc?: number;
  /**
   * Delivery charge by merchant on product, item, ticket, etc.
   *
   * @currency Rupees
   * @default 0
   */
  pdc?: number;
  /**
   * A unique ID of product, item, ticket, etc.
   */
  pid: string;
};

export type EsewaRequestPayload = Required<EsewaInit> & {
  /**
   * Total payment amount including tax, service and deliver charge.
   * i.e tAmt = amt rn+ txAmt + psc + tAmt
   *
   * @currency Rupees
   */
  tAmt: number;
  /**
   * Merchant code provided by eSewa
   */
  scd: string;
  /**
   * Success URL: a redirect URL of merchant application where
   * customer will be redirected after SUCCESSFUL transaction.
   */
  su: string;
  /**
   * Failure URL: a redirect URL of merchant application where
   * customer will be redirected after FAILURE or PENDING transaction.
   */
  fu: string;
};

export type VerificationPayload = {
  /**
   * Total payment amount of product or service
   *
   * @currency Rupees
   */
  amt: string;
  /**
   * Merchant code provided by eSewa
   */
  scd: string;
  /**
   * A unique ID of product or item or ticket etc generated by merchant for payment
   */
  pid: string;
  /**
   * A unique payment reference code from eSewa generated on SUCCESSFUL transaction
   */
  rid: string;
};

export type EsewaVerifyResponse =
  | {
      success: true;
      code: 'success' | 'failure';
    }
  | {
      success: false;
      error: string;
    };

export type EsewaSuccessSearchParams = {
  /**
   * Product ID (pid) used on payment request
   */
  oid: string;
  /**
   * Total payment amount (tAmt)
   *
   * @currency Rupees
   */
  amt: string;
  /**
   * A unique payment reference code generated by eSewa
   */
  refId: string;
};
