type KhaltiCustomerInfo = {
  /**
   * Name of the customer.
   */
  name: string;
  /**
   * Email of the customer.
   */
  email: string;
  /**
   * Phone number of the customer.
   */
  phone: string;
};

type KhaltiAmountBreakdown = {
  /**
   * Label of the amount.
   */
  label: string;
  /**
   * @currency Paisa
   */
  amount: number;
};

type KhaltiProductDetails = {
  /**
   * Unique identifier for the product.
   */
  identity: string;
  /**
   * Name of the product.
   */
  name: string;
  /**
   * Price of the product.
   *
   * @currency Paisa
   */
  total_price: number;
  /**
   * Quantity of the product.
   */
  quantity: number;
  /**
   * Price of the product per unit.
   *
   * @currency Paisa
   */
  unit_price: number;
};

export type KhaltiInit = {
  /**
   * Total payable amount excluding the service charge.
   *
   * @currency Paisa
   */
  amount: number;
  /**
   * Unique identifier for the transaction generated by merchant.
   */
  purchase_order_id: string;
  /**
   * This is the name of the product.
   */
  purchase_order_name: string;
  /**
   * This field represents to whom the txn is going to be billed to.
   */
  customer_info?: KhaltiCustomerInfo;
  /**
   * Any number of labels and amounts can be passed.
   */
  amount_breakdown?: Array<KhaltiAmountBreakdown>;
  /**
   * Number of set is unlimited.
   */
  product_details?: Array<KhaltiProductDetails>;
};

export type KhaltiInitSuccessResponse = {
  /**
   * The initial payment identifier.
   */
  pidx: string;
  /**
   * The URL of the payment page that the user should be redirected to
   * after the success response.
   */
  payment_url: string;
  /**
   * The time when the payment URL expires.
   */
  expires_at: string;
  /**
   * The time in seconds after which the payment URL expires.
   */
  expires_in: string;
};

type GenericKhaltiErrors = {
  detail: string;
} & (
  | {
      status_code: number | string;
      error_key?: never;
    }
  | {
      status_code?: never;
      error_key: string;
    }
);

type KhaltiInitError = {
  error_key: 'validation_error';
} & (
  | {
      return_url: Array<string>;
    }
  | {
      webslite_url: Array<string>;
    }
  | {
      amount: Array<string>;
    }
  | {
      purchase_order_id: Array<string>;
    }
  | {
      purchase_order_name: Array<string>;
    }
);

type KhatiInitErrorResponse = KhaltiInitError | GenericKhaltiErrors;

export type KhaltiInitResponse =
  | KhaltiInitSuccessResponse
  | KhatiInitErrorResponse;

export type KhaltiInitRequestPayload = KhaltiInit & {
  /**
   * Landing page after the transaction.
   *
   * @type URL
   */
  return_url: string;
  /**
   * The URL of the website.
   *
   * @type URL
   */
  website_url: string;
};
